version: '3'
services:
    front-end:
        build: .
        image: moviesurfer:latest
        command: npm run dev
        environment: 
          - REACT_APP_API_BASE_URL=http://localhost:8080/api
        ports:
          - '3000:3000'
        volumes:
          - '.:/usr/src/app'
          - /usr/src/app/node_modules
